# Site settings
title: Ada Discovery Analytics
email: peter.banda@protonmail.com
copyright_name: Ada Discovery Analytics
github_username: peterbanda

collections:
  packages :
  citation :
  collaborators :

include:
  - CONTRIBUTING.md
  - README.md

# used to estimate reading time
wpm: 150

port: 4444
permalink: /:title

baseurl: 

# jekyll-paginate
paginate: 5
paginate_path: /page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
